name: test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3-dev python3-setuptools && \
        pip3 install -U pip && \
        pip3 install codecov && \
        pip3 install -U -r test-requirements.txt && \
        pylint -E *py && \
        pytype *py && \
        PYTHONPATH=. coverage run test_pipette.py && \
        coverage report pipette.py
    - name: docker-test
      run: |
        docker build -f Dockerfile -t cyberreboot/pipette .
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
